apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template1
  title: Main Application Template
  description: A template that creates an application and triggers additional setup
  tags:
    - nodejs
    - react
spec:
  owner: group:development
  type: service
  
  parameters:
    - title: Application Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name for the application
          ui:autofocus: true
          ui:options:
            rows: 1
        description:
          title: Description
          type: string
          description: A short description of the application
        enableDatabase:
          title: Enable Database Setup
          type: boolean
          description: Trigger database setup template
          default: true
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
  
  steps:
    - id: log-start
      name: Log Start
      action: debug:log
      input:
        message: 'Starting template execution for: ${{ parameters.name }}'
    
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
    
    - id: create-repo
      name: Create Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=your-org&repo=${{ parameters.name }}
        repoVisibility: private
    
    # Custom action: Trigger Template 2 if database is enabled
    - id: trigger-database-setup
      name: Trigger Database Setup Template
      if: ${{ parameters.enableDatabase }}
      action: trigger:template
      input:
        templateRef: 'template:default/template2'
        values:
          applicationName: ${{ parameters.name }}
          databaseType: postgresql
          owner: ${{ parameters.owner }}
    
    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  
  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: Database Setup Task
        url: ${{ steps['trigger-database-setup'].output.taskUrl }}
        icon: dashboard
